// GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate with: dart run scripts/bake_models_catalog.dart
//
// Baked snapshot of every quant + voicepack discovered via
// the HF API for each `BackendRepo` in `model_service.dart`.
// Loaded at app boot via `getWhisperCppModels()` so the model
// picker is fully populated without a network probe.
//
// Sizes are real (from HF), so the existence-check in
// `_isModelDownloaded` is unaffected.

// ignore_for_file: lines_longer_than_80_chars

import 'model_service.dart';

const Map<String, ModelDefinition> bakedDiscoveredModels = {
  'parakeet-tdt-0.6b-v3-q4_k': ModelDefinition(
    name: 'parakeet-tdt-0.6b-v3-q4_k',
    displayName: 'Parakeet TDT 0.6B v3 (q4_k)',
    fileName: 'parakeet-tdt-0.6b-v3-q4_k.gguf',
    url: 'https://huggingface.co/cstr/parakeet-tdt-0.6b-v3-GGUF/resolve/main/parakeet-tdt-0.6b-v3-q4_k.gguf',
    sizeBytes: 488674176,
    checksum: '',
    description: 'Fast English ASR (NVIDIA Parakeet) — 466.0 MB',
    quantization: 'q4_k',
    backend: 'parakeet',
    kind: ModelKind.asr,
  ),
  'parakeet-tdt-0.6b-v3-q5_0': ModelDefinition(
    name: 'parakeet-tdt-0.6b-v3-q5_0',
    displayName: 'Parakeet TDT 0.6B v3 (q5_0)',
    fileName: 'parakeet-tdt-0.6b-v3-q5_0.gguf',
    url: 'https://huggingface.co/cstr/parakeet-tdt-0.6b-v3-GGUF/resolve/main/parakeet-tdt-0.6b-v3-q5_0.gguf',
    sizeBytes: 541034656,
    checksum: '',
    description: 'Fast English ASR (NVIDIA Parakeet) — 516.0 MB',
    quantization: 'q5_0',
    backend: 'parakeet',
    kind: ModelKind.asr,
  ),
  'parakeet-tdt-0.6b-v3-q8_0': ModelDefinition(
    name: 'parakeet-tdt-0.6b-v3-q8_0',
    displayName: 'Parakeet TDT 0.6B v3 (q8_0)',
    fileName: 'parakeet-tdt-0.6b-v3-q8_0.gguf',
    url: 'https://huggingface.co/cstr/parakeet-tdt-0.6b-v3-GGUF/resolve/main/parakeet-tdt-0.6b-v3-q8_0.gguf',
    sizeBytes: 745121600,
    checksum: '',
    description: 'Fast English ASR (NVIDIA Parakeet) — 710.6 MB',
    quantization: 'q8_0',
    backend: 'parakeet',
    kind: ModelKind.asr,
  ),
  'parakeet-tdt-0.6b-v3-f16': ModelDefinition(
    name: 'parakeet-tdt-0.6b-v3-f16',
    displayName: 'Parakeet TDT 0.6B v3 (f16)',
    fileName: 'parakeet-tdt-0.6b-v3.gguf',
    url: 'https://huggingface.co/cstr/parakeet-tdt-0.6b-v3-GGUF/resolve/main/parakeet-tdt-0.6b-v3.gguf',
    sizeBytes: 1255338816,
    checksum: '',
    description: 'Fast English ASR (NVIDIA Parakeet) — 1.17 GB',
    quantization: 'f16',
    backend: 'parakeet',
    kind: ModelKind.asr,
  ),
  'canary-1b-v2-q4_k': ModelDefinition(
    name: 'canary-1b-v2-q4_k',
    displayName: 'Canary 1B v2 (q4_k)',
    fileName: 'canary-1b-v2-q4_k.gguf',
    url: 'https://huggingface.co/cstr/canary-1b-v2-GGUF/resolve/main/canary-1b-v2-q4_k.gguf',
    sizeBytes: 705118368,
    checksum: '',
    description: 'NVIDIA Canary — speech translation — 672.5 MB',
    quantization: 'q4_k',
    backend: 'canary',
    kind: ModelKind.asr,
  ),
  'canary-1b-v2-q5_0': ModelDefinition(
    name: 'canary-1b-v2-q5_0',
    displayName: 'Canary 1B v2 (q5_0)',
    fileName: 'canary-1b-v2-q5_0.gguf',
    url: 'https://huggingface.co/cstr/canary-1b-v2-GGUF/resolve/main/canary-1b-v2-q5_0.gguf',
    sizeBytes: 814694560,
    checksum: '',
    description: 'NVIDIA Canary — speech translation — 777.0 MB',
    quantization: 'q5_0',
    backend: 'canary',
    kind: ModelKind.asr,
  ),
  'canary-1b-v2-q8_0': ModelDefinition(
    name: 'canary-1b-v2-q8_0',
    displayName: 'Canary 1B v2 (q8_0)',
    fileName: 'canary-1b-v2-q8_0.gguf',
    url: 'https://huggingface.co/cstr/canary-1b-v2-GGUF/resolve/main/canary-1b-v2-q8_0.gguf',
    sizeBytes: 1143423136,
    checksum: '',
    description: 'NVIDIA Canary — speech translation — 1.06 GB',
    quantization: 'q8_0',
    backend: 'canary',
    kind: ModelKind.asr,
  ),
  'canary-1b-v2-f16': ModelDefinition(
    name: 'canary-1b-v2-f16',
    displayName: 'Canary 1B v2 (f16)',
    fileName: 'canary-1b-v2.gguf',
    url: 'https://huggingface.co/cstr/canary-1b-v2-GGUF/resolve/main/canary-1b-v2.gguf',
    sizeBytes: 1965244512,
    checksum: '',
    description: 'NVIDIA Canary — speech translation — 1.83 GB',
    quantization: 'f16',
    backend: 'canary',
    kind: ModelKind.asr,
  ),
  'cohere-transcribe-q4_k': ModelDefinition(
    name: 'cohere-transcribe-q4_k',
    displayName: 'Cohere Transcribe (q4_k)',
    fileName: 'cohere-transcribe-q4_k.gguf',
    url: 'https://huggingface.co/cstr/cohere-transcribe-03-2026-GGUF/resolve/main/cohere-transcribe-q4_k.gguf',
    sizeBytes: 1510362752,
    checksum: '',
    description: 'Cohere high-accuracy ASR — 1.41 GB',
    quantization: 'q4_k',
    backend: 'cohere',
    kind: ModelKind.asr,
  ),
  'cohere-transcribe-q5_0': ModelDefinition(
    name: 'cohere-transcribe-q5_0',
    displayName: 'Cohere Transcribe (q5_0)',
    fileName: 'cohere-transcribe-q5_0.gguf',
    url: 'https://huggingface.co/cstr/cohere-transcribe-03-2026-GGUF/resolve/main/cohere-transcribe-q5_0.gguf',
    sizeBytes: 1738722944,
    checksum: '',
    description: 'Cohere high-accuracy ASR — 1.62 GB',
    quantization: 'q5_0',
    backend: 'cohere',
    kind: ModelKind.asr,
  ),
  'cohere-transcribe-q5_1': ModelDefinition(
    name: 'cohere-transcribe-q5_1',
    displayName: 'Cohere Transcribe (q5_1)',
    fileName: 'cohere-transcribe-q5_1.gguf',
    url: 'https://huggingface.co/cstr/cohere-transcribe-03-2026-GGUF/resolve/main/cohere-transcribe-q5_1.gguf',
    sizeBytes: 1852903040,
    checksum: '',
    description: 'Cohere high-accuracy ASR — 1.73 GB',
    quantization: 'q5_1',
    backend: 'cohere',
    kind: ModelKind.asr,
  ),
  'cohere-transcribe-q6_k': ModelDefinition(
    name: 'cohere-transcribe-q6_k',
    displayName: 'Cohere Transcribe (q6_k)',
    fileName: 'cohere-transcribe-q6_k.gguf',
    url: 'https://huggingface.co/cstr/cohere-transcribe-03-2026-GGUF/resolve/main/cohere-transcribe-q6_k.gguf',
    sizeBytes: 1981355648,
    checksum: '',
    description: 'Cohere high-accuracy ASR — 1.85 GB',
    quantization: 'q6_k',
    backend: 'cohere',
    kind: ModelKind.asr,
  ),
  'cohere-transcribe-q8_0': ModelDefinition(
    name: 'cohere-transcribe-q8_0',
    displayName: 'Cohere Transcribe (q8_0)',
    fileName: 'cohere-transcribe-q8_0.gguf',
    url: 'https://huggingface.co/cstr/cohere-transcribe-03-2026-GGUF/resolve/main/cohere-transcribe-q8_0.gguf',
    sizeBytes: 2423803520,
    checksum: '',
    description: 'Cohere high-accuracy ASR — 2.26 GB',
    quantization: 'q8_0',
    backend: 'cohere',
    kind: ModelKind.asr,
  ),
  'cohere-transcribe-f16': ModelDefinition(
    name: 'cohere-transcribe-f16',
    displayName: 'Cohere Transcribe (f16)',
    fileName: 'cohere-transcribe.gguf',
    url: 'https://huggingface.co/cstr/cohere-transcribe-03-2026-GGUF/resolve/main/cohere-transcribe.gguf',
    sizeBytes: 4136504896,
    checksum: '',
    description: 'Cohere high-accuracy ASR — 3.85 GB',
    quantization: 'f16',
    backend: 'cohere',
    kind: ModelKind.asr,
  ),
  'voxtral-mini-3b-2507-q4_k': ModelDefinition(
    name: 'voxtral-mini-3b-2507-q4_k',
    displayName: 'Voxtral Mini 3B 2507 (q4_k)',
    fileName: 'voxtral-mini-3b-2507-q4_k.gguf',
    url: 'https://huggingface.co/cstr/voxtral-mini-3b-2507-GGUF/resolve/main/voxtral-mini-3b-2507-q4_k.gguf',
    sizeBytes: 2652639968,
    checksum: '',
    description: 'Mistral Voxtral — speech translation + ASR — 2.47 GB',
    quantization: 'q4_k',
    backend: 'voxtral',
    kind: ModelKind.asr,
  ),
  'voxtral-mini-3b-2507-q8_0': ModelDefinition(
    name: 'voxtral-mini-3b-2507-q8_0',
    displayName: 'Voxtral Mini 3B 2507 (q8_0)',
    fileName: 'voxtral-mini-3b-2507-q8_0.gguf',
    url: 'https://huggingface.co/cstr/voxtral-mini-3b-2507-GGUF/resolve/main/voxtral-mini-3b-2507-q8_0.gguf',
    sizeBytes: 4986770144,
    checksum: '',
    description: 'Mistral Voxtral — speech translation + ASR — 4.64 GB',
    quantization: 'q8_0',
    backend: 'voxtral',
    kind: ModelKind.asr,
  ),
  'voxtral-mini-4b-realtime-q4_k': ModelDefinition(
    name: 'voxtral-mini-4b-realtime-q4_k',
    displayName: 'Voxtral Mini 4B realtime (q4_k)',
    fileName: 'voxtral-mini-4b-realtime-q4_k.gguf',
    url: 'https://huggingface.co/cstr/voxtral-mini-4b-realtime-GGUF/resolve/main/voxtral-mini-4b-realtime-q4_k.gguf',
    sizeBytes: 2524137216,
    checksum: '',
    description: 'Voxtral realtime variant — 2.35 GB',
    quantization: 'q4_k',
    backend: 'voxtral4b',
    kind: ModelKind.asr,
  ),
  'voxtral-mini-4b-realtime-q8_0': ModelDefinition(
    name: 'voxtral-mini-4b-realtime-q8_0',
    displayName: 'Voxtral Mini 4B realtime (q8_0)',
    fileName: 'voxtral-mini-4b-realtime-q8_0.gguf',
    url: 'https://huggingface.co/cstr/voxtral-mini-4b-realtime-GGUF/resolve/main/voxtral-mini-4b-realtime-q8_0.gguf',
    sizeBytes: 4733486848,
    checksum: '',
    description: 'Voxtral realtime variant — 4.41 GB',
    quantization: 'q8_0',
    backend: 'voxtral4b',
    kind: ModelKind.asr,
  ),
  'qwen3-asr-0.6b-q4_k': ModelDefinition(
    name: 'qwen3-asr-0.6b-q4_k',
    displayName: 'Qwen3-ASR 0.6B (q4_k)',
    fileName: 'qwen3-asr-0.6b-q4_k.gguf',
    url: 'https://huggingface.co/cstr/qwen3-asr-0.6b-GGUF/resolve/main/qwen3-asr-0.6b-q4_k.gguf',
    sizeBytes: 540021408,
    checksum: '',
    description: 'Multilingual (30+ langs incl. Chinese dialects) — 515.0 MB',
    quantization: 'q4_k',
    backend: 'qwen3',
    kind: ModelKind.asr,
  ),
  'qwen3-asr-0.6b-q8_0': ModelDefinition(
    name: 'qwen3-asr-0.6b-q8_0',
    displayName: 'Qwen3-ASR 0.6B (q8_0)',
    fileName: 'qwen3-asr-0.6b-q8_0.gguf',
    url: 'https://huggingface.co/cstr/qwen3-asr-0.6b-GGUF/resolve/main/qwen3-asr-0.6b-q8_0.gguf',
    sizeBytes: 1006809760,
    checksum: '',
    description: 'Multilingual (30+ langs incl. Chinese dialects) — 960.2 MB',
    quantization: 'q8_0',
    backend: 'qwen3',
    kind: ModelKind.asr,
  ),
  'qwen3-asr-0.6b-f16': ModelDefinition(
    name: 'qwen3-asr-0.6b-f16',
    displayName: 'Qwen3-ASR 0.6B (f16)',
    fileName: 'qwen3-asr-0.6b.gguf',
    url: 'https://huggingface.co/cstr/qwen3-asr-0.6b-GGUF/resolve/main/qwen3-asr-0.6b.gguf',
    sizeBytes: 1882037824,
    checksum: '',
    description: 'Multilingual (30+ langs incl. Chinese dialects) — 1.75 GB',
    quantization: 'f16',
    backend: 'qwen3',
    kind: ModelKind.asr,
  ),
  'granite-speech-4.0-1b-f16': ModelDefinition(
    name: 'granite-speech-4.0-1b-f16',
    displayName: 'Granite 4.0 1B Speech (f16)',
    fileName: 'granite-speech-4.0-1b-f16.gguf',
    url: 'https://huggingface.co/cstr/granite-speech-4.0-1b-GGUF/resolve/main/granite-speech-4.0-1b-f16.gguf',
    sizeBytes: 5581887520,
    checksum: '',
    description: 'IBM Granite speech (instruction-tuned) — 5.20 GB',
    quantization: 'f16',
    backend: 'granite',
    kind: ModelKind.asr,
  ),
  'granite-speech-4.0-1b-q4_k': ModelDefinition(
    name: 'granite-speech-4.0-1b-q4_k',
    displayName: 'Granite 4.0 1B Speech (q4_k)',
    fileName: 'granite-speech-4.0-1b-q4_k.gguf',
    url: 'https://huggingface.co/cstr/granite-speech-4.0-1b-GGUF/resolve/main/granite-speech-4.0-1b-q4_k.gguf',
    sizeBytes: 2941043072,
    checksum: '',
    description: 'IBM Granite speech (instruction-tuned) — 2.74 GB',
    quantization: 'q4_k',
    backend: 'granite',
    kind: ModelKind.asr,
  ),
  'granite-speech-4.0-1b-q5_0': ModelDefinition(
    name: 'granite-speech-4.0-1b-q5_0',
    displayName: 'Granite 4.0 1B Speech (q5_0)',
    fileName: 'granite-speech-4.0-1b-q5_0.gguf',
    url: 'https://huggingface.co/cstr/granite-speech-4.0-1b-GGUF/resolve/main/granite-speech-4.0-1b-q5_0.gguf',
    sizeBytes: 3170681728,
    checksum: '',
    description: 'IBM Granite speech (instruction-tuned) — 2.95 GB',
    quantization: 'q5_0',
    backend: 'granite',
    kind: ModelKind.asr,
  ),
  'granite-speech-4.0-1b-q8_0': ModelDefinition(
    name: 'granite-speech-4.0-1b-q8_0',
    displayName: 'Granite 4.0 1B Speech (q8_0)',
    fileName: 'granite-speech-4.0-1b-q8_0.gguf',
    url: 'https://huggingface.co/cstr/granite-speech-4.0-1b-GGUF/resolve/main/granite-speech-4.0-1b-q8_0.gguf',
    sizeBytes: 3859597696,
    checksum: '',
    description: 'IBM Granite speech (instruction-tuned) — 3.59 GB',
    quantization: 'q8_0',
    backend: 'granite',
    kind: ModelKind.asr,
  ),
  'stt-en-fastconformer-ctc-large-f16': ModelDefinition(
    name: 'stt-en-fastconformer-ctc-large-f16',
    displayName: 'FastConformer CTC (en) (f16)',
    fileName: 'stt-en-fastconformer-ctc-large-f16.gguf',
    url: 'https://huggingface.co/cstr/stt-en-fastconformer-ctc-large-GGUF/resolve/main/stt-en-fastconformer-ctc-large-f16.gguf',
    sizeBytes: 232018080,
    checksum: '',
    description: 'Low-latency CTC ASR (English) — 221.3 MB',
    quantization: 'f16',
    backend: 'fastconformer-ctc',
    kind: ModelKind.asr,
  ),
  'stt-en-fastconformer-ctc-large-q4_k': ModelDefinition(
    name: 'stt-en-fastconformer-ctc-large-q4_k',
    displayName: 'FastConformer CTC (en) (q4_k)',
    fileName: 'stt-en-fastconformer-ctc-large-q4_k.gguf',
    url: 'https://huggingface.co/cstr/stt-en-fastconformer-ctc-large-GGUF/resolve/main/stt-en-fastconformer-ctc-large-q4_k.gguf',
    sizeBytes: 86937088,
    checksum: '',
    description: 'Low-latency CTC ASR (English) — 82.9 MB',
    quantization: 'q4_k',
    backend: 'fastconformer-ctc',
    kind: ModelKind.asr,
  ),
  'stt-en-fastconformer-ctc-large-q5_0': ModelDefinition(
    name: 'stt-en-fastconformer-ctc-large-q5_0',
    displayName: 'FastConformer CTC (en) (q5_0)',
    fileName: 'stt-en-fastconformer-ctc-large-q5_0.gguf',
    url: 'https://huggingface.co/cstr/stt-en-fastconformer-ctc-large-GGUF/resolve/main/stt-en-fastconformer-ctc-large-q5_0.gguf',
    sizeBytes: 99552832,
    checksum: '',
    description: 'Low-latency CTC ASR (English) — 94.9 MB',
    quantization: 'q5_0',
    backend: 'fastconformer-ctc',
    kind: ModelKind.asr,
  ),
  'stt-en-fastconformer-ctc-large-q8_0': ModelDefinition(
    name: 'stt-en-fastconformer-ctc-large-q8_0',
    displayName: 'FastConformer CTC (en) (q8_0)',
    fileName: 'stt-en-fastconformer-ctc-large-q8_0.gguf',
    url: 'https://huggingface.co/cstr/stt-en-fastconformer-ctc-large-GGUF/resolve/main/stt-en-fastconformer-ctc-large-q8_0.gguf',
    sizeBytes: 137400064,
    checksum: '',
    description: 'Low-latency CTC ASR (English) — 131.0 MB',
    quantization: 'q8_0',
    backend: 'fastconformer-ctc',
    kind: ModelKind.asr,
  ),
  'wav2vec2-xlsr-en-q4_k': ModelDefinition(
    name: 'wav2vec2-xlsr-en-q4_k',
    displayName: 'Wav2Vec2 base (en) (q4_k)',
    fileName: 'wav2vec2-xlsr-en-q4_k.gguf',
    url: 'https://huggingface.co/cstr/wav2vec2-large-xlsr-53-english-GGUF/resolve/main/wav2vec2-xlsr-en-q4_k.gguf',
    sizeBytes: 221901472,
    checksum: '',
    description: 'Self-supervised (facebook/wav2vec2) — 211.6 MB',
    quantization: 'q4_k',
    backend: 'wav2vec2',
    kind: ModelKind.asr,
  ),
  'wav2vec2-xlsr-en-q5_0': ModelDefinition(
    name: 'wav2vec2-xlsr-en-q5_0',
    displayName: 'Wav2Vec2 base (en) (q5_0)',
    fileName: 'wav2vec2-xlsr-en-q5_0.gguf',
    url: 'https://huggingface.co/cstr/wav2vec2-large-xlsr-53-english-GGUF/resolve/main/wav2vec2-xlsr-en-q5_0.gguf',
    sizeBytes: 259719968,
    checksum: '',
    description: 'Self-supervised (facebook/wav2vec2) — 247.7 MB',
    quantization: 'q5_0',
    backend: 'wav2vec2',
    kind: ModelKind.asr,
  ),
  'wav2vec2-xlsr-en-q8_0': ModelDefinition(
    name: 'wav2vec2-xlsr-en-q8_0',
    displayName: 'Wav2Vec2 base (en) (q8_0)',
    fileName: 'wav2vec2-xlsr-en-q8_0.gguf',
    url: 'https://huggingface.co/cstr/wav2vec2-large-xlsr-53-english-GGUF/resolve/main/wav2vec2-xlsr-en-q8_0.gguf',
    sizeBytes: 373175456,
    checksum: '',
    description: 'Self-supervised (facebook/wav2vec2) — 355.9 MB',
    quantization: 'q8_0',
    backend: 'wav2vec2',
    kind: ModelKind.asr,
  ),
  'wav2vec2-xlsr-en-f16': ModelDefinition(
    name: 'wav2vec2-xlsr-en-f16',
    displayName: 'Wav2Vec2 base (en) (f16)',
    fileName: 'wav2vec2-xlsr-en.gguf',
    url: 'https://huggingface.co/cstr/wav2vec2-large-xlsr-53-english-GGUF/resolve/main/wav2vec2-xlsr-en.gguf',
    sizeBytes: 656881696,
    checksum: '',
    description: 'Self-supervised (facebook/wav2vec2) — 626.5 MB',
    quantization: 'f16',
    backend: 'wav2vec2',
    kind: ModelKind.asr,
  ),
  'omniasr-llm-300m-v2-f16': ModelDefinition(
    name: 'omniasr-llm-300m-v2-f16',
    displayName: 'OmniASR LLM 300M v2 (f16)',
    fileName: 'omniasr-llm-300m-v2-f16.gguf',
    url: 'https://huggingface.co/cstr/omniasr-llm-300m-v2-GGUF/resolve/main/omniasr-llm-300m-v2-f16.gguf',
    sizeBytes: 3256256480,
    checksum: '',
    description: 'Multilingual LLM-based ASR with `lang=` hint — 3.03 GB',
    quantization: 'f16',
    backend: 'omniasr-llm',
    kind: ModelKind.asr,
  ),
  'omniasr-llm-300m-v2-q4_k': ModelDefinition(
    name: 'omniasr-llm-300m-v2-q4_k',
    displayName: 'OmniASR LLM 300M v2 (q4_k)',
    fileName: 'omniasr-llm-300m-v2-q4_k.gguf',
    url: 'https://huggingface.co/cstr/omniasr-llm-300m-v2-GGUF/resolve/main/omniasr-llm-300m-v2-q4_k.gguf',
    sizeBytes: 1067616288,
    checksum: '',
    description: 'Multilingual LLM-based ASR with `lang=` hint — 1018.2 MB',
    quantization: 'q4_k',
    backend: 'omniasr-llm',
    kind: ModelKind.asr,
  ),
  'omniasr-llm-300m-v2-q8_0': ModelDefinition(
    name: 'omniasr-llm-300m-v2-q8_0',
    displayName: 'OmniASR LLM 300M v2 (q8_0)',
    fileName: 'omniasr-llm-300m-v2-q8_0.gguf',
    url: 'https://huggingface.co/cstr/omniasr-llm-300m-v2-GGUF/resolve/main/omniasr-llm-300m-v2-q8_0.gguf',
    sizeBytes: 1836658368,
    checksum: '',
    description: 'Multilingual LLM-based ASR with `lang=` hint — 1.71 GB',
    quantization: 'q8_0',
    backend: 'omniasr-llm',
    kind: ModelKind.asr,
  ),
  'firered-asr2-aed-q4_k': ModelDefinition(
    name: 'firered-asr2-aed-q4_k',
    displayName: 'FireRed ASR2 AED (q4_k)',
    fileName: 'firered-asr2-aed-q4_k.gguf',
    url: 'https://huggingface.co/cstr/firered-asr2-aed-GGUF/resolve/main/firered-asr2-aed-q4_k.gguf',
    sizeBytes: 962807328,
    checksum: '',
    description: 'FireRed AED ASR (Chinese + English) — 918.2 MB',
    quantization: 'q4_k',
    backend: 'firered-asr',
    kind: ModelKind.asr,
  ),
  'firered-asr2-aed-q8_0': ModelDefinition(
    name: 'firered-asr2-aed-q8_0',
    displayName: 'FireRed ASR2 AED (q8_0)',
    fileName: 'firered-asr2-aed-q8_0.gguf',
    url: 'https://huggingface.co/cstr/firered-asr2-aed-GGUF/resolve/main/firered-asr2-aed-q8_0.gguf',
    sizeBytes: 1464803488,
    checksum: '',
    description: 'FireRed AED ASR (Chinese + English) — 1.36 GB',
    quantization: 'q8_0',
    backend: 'firered-asr',
    kind: ModelKind.asr,
  ),
  'firered-asr2-aed-f16': ModelDefinition(
    name: 'firered-asr2-aed-f16',
    displayName: 'FireRed ASR2 AED (f16)',
    fileName: 'firered-asr2-aed.gguf',
    url: 'https://huggingface.co/cstr/firered-asr2-aed-GGUF/resolve/main/firered-asr2-aed.gguf',
    sizeBytes: 2406046176,
    checksum: '',
    description: 'FireRed AED ASR (Chinese + English) — 2.24 GB',
    quantization: 'f16',
    backend: 'firered-asr',
    kind: ModelKind.asr,
  ),
  'kyutai-stt-1b-q4_k': ModelDefinition(
    name: 'kyutai-stt-1b-q4_k',
    displayName: 'Kyutai STT 1B (q4_k)',
    fileName: 'kyutai-stt-1b-q4_k.gguf',
    url: 'https://huggingface.co/cstr/kyutai-stt-1b-GGUF/resolve/main/kyutai-stt-1b-q4_k.gguf',
    sizeBytes: 666565184,
    checksum: '',
    description: 'Kyutai streaming STT — 635.7 MB',
    quantization: 'q4_k',
    backend: 'kyutai-stt',
    kind: ModelKind.asr,
  ),
  'kyutai-stt-1b-q8_0': ModelDefinition(
    name: 'kyutai-stt-1b-q8_0',
    displayName: 'Kyutai STT 1B (q8_0)',
    fileName: 'kyutai-stt-1b-q8_0.gguf',
    url: 'https://huggingface.co/cstr/kyutai-stt-1b-GGUF/resolve/main/kyutai-stt-1b-q8_0.gguf',
    sizeBytes: 1173716544,
    checksum: '',
    description: 'Kyutai streaming STT — 1.09 GB',
    quantization: 'q8_0',
    backend: 'kyutai-stt',
    kind: ModelKind.asr,
  ),
  'kyutai-stt-1b-f16': ModelDefinition(
    name: 'kyutai-stt-1b-f16',
    displayName: 'Kyutai STT 1B (f16)',
    fileName: 'kyutai-stt-1b.gguf',
    url: 'https://huggingface.co/cstr/kyutai-stt-1b-GGUF/resolve/main/kyutai-stt-1b.gguf',
    sizeBytes: 2124625824,
    checksum: '',
    description: 'Kyutai streaming STT — 1.98 GB',
    quantization: 'f16',
    backend: 'kyutai-stt',
    kind: ModelKind.asr,
  ),
  'glm-asr-nano-q4_k': ModelDefinition(
    name: 'glm-asr-nano-q4_k',
    displayName: 'GLM-ASR Nano (q4_k)',
    fileName: 'glm-asr-nano-q4_k.gguf',
    url: 'https://huggingface.co/cstr/glm-asr-nano-GGUF/resolve/main/glm-asr-nano-q4_k.gguf',
    sizeBytes: 1323308256,
    checksum: '',
    description: 'GLM-family multilingual ASR — 1.23 GB',
    quantization: 'q4_k',
    backend: 'glm-asr',
    kind: ModelKind.asr,
  ),
  'glm-asr-nano-q8_0': ModelDefinition(
    name: 'glm-asr-nano-q8_0',
    displayName: 'GLM-ASR Nano (q8_0)',
    fileName: 'glm-asr-nano-q8_0.gguf',
    url: 'https://huggingface.co/cstr/glm-asr-nano-GGUF/resolve/main/glm-asr-nano-q8_0.gguf',
    sizeBytes: 2434536672,
    checksum: '',
    description: 'GLM-family multilingual ASR — 2.27 GB',
    quantization: 'q8_0',
    backend: 'glm-asr',
    kind: ModelKind.asr,
  ),
  'glm-asr-nano-f16': ModelDefinition(
    name: 'glm-asr-nano-f16',
    displayName: 'GLM-ASR Nano (f16)',
    fileName: 'glm-asr-nano.gguf',
    url: 'https://huggingface.co/cstr/glm-asr-nano-GGUF/resolve/main/glm-asr-nano.gguf',
    sizeBytes: 4518089888,
    checksum: '',
    description: 'GLM-family multilingual ASR — 4.21 GB',
    quantization: 'f16',
    backend: 'glm-asr',
    kind: ModelKind.asr,
  ),
  'vibevoice-asr-f16': ModelDefinition(
    name: 'vibevoice-asr-f16',
    displayName: 'VibeVoice ASR (f16)',
    fileName: 'vibevoice-asr-f16.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-asr-GGUF/resolve/main/vibevoice-asr-f16.gguf',
    sizeBytes: 16664915264,
    checksum: '',
    description: 'Multilingual large ASR (~4.5 GB) — 15.52 GB',
    quantization: 'f16',
    backend: 'vibevoice',
    kind: ModelKind.asr,
  ),
  'vibevoice-asr-q4_k': ModelDefinition(
    name: 'vibevoice-asr-q4_k',
    displayName: 'VibeVoice ASR (q4_k)',
    fileName: 'vibevoice-asr-q4_k.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-asr-GGUF/resolve/main/vibevoice-asr-q4_k.gguf',
    sizeBytes: 4811829376,
    checksum: '',
    description: 'Multilingual large ASR (~4.5 GB) — 4.48 GB',
    quantization: 'q4_k',
    backend: 'vibevoice',
    kind: ModelKind.asr,
  ),
  'vibevoice-realtime-0.5b-q4_k': ModelDefinition(
    name: 'vibevoice-realtime-0.5b-q4_k',
    displayName: 'VibeVoice Realtime 0.5B (q4_k)',
    fileName: 'vibevoice-realtime-0.5b-q4_k.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-realtime-0.5b-q4_k.gguf',
    sizeBytes: 635731136,
    checksum: '',
    description: 'VibeVoice realtime TTS — 606.3 MB',
    quantization: 'q4_k',
    backend: 'vibevoice-tts',
    kind: ModelKind.tts,
  ),
  'vibevoice-realtime-0.5b-q8_0': ModelDefinition(
    name: 'vibevoice-realtime-0.5b-q8_0',
    displayName: 'VibeVoice Realtime 0.5B (q8_0)',
    fileName: 'vibevoice-realtime-0.5b-q8_0.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-realtime-0.5b-q8_0.gguf',
    sizeBytes: 1123647552,
    checksum: '',
    description: 'VibeVoice realtime TTS — 1.05 GB',
    quantization: 'q8_0',
    backend: 'vibevoice-tts',
    kind: ModelKind.tts,
  ),
  'vibevoice-realtime-0.5b-tts-f16': ModelDefinition(
    name: 'vibevoice-realtime-0.5b-tts-f16',
    displayName: 'VibeVoice Realtime 0.5B (tts-f16)',
    fileName: 'vibevoice-realtime-0.5b-tts-f16.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-realtime-0.5b-tts-f16.gguf',
    sizeBytes: 2038490752,
    checksum: '',
    description: 'VibeVoice realtime TTS — 1.90 GB',
    quantization: 'tts-f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.tts,
  ),
  'vibevoice-voice-de-Spk0_man': ModelDefinition(
    name: 'vibevoice-voice-de-Spk0_man',
    displayName: 'VibeVoice Realtime 0.5B voice — de-Spk0_man',
    fileName: 'vibevoice-voice-de-Spk0_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-de-Spk0_man.gguf',
    sizeBytes: 5698144,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 5.4 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-de-Spk1_woman': ModelDefinition(
    name: 'vibevoice-voice-de-Spk1_woman',
    displayName: 'VibeVoice Realtime 0.5B voice — de-Spk1_woman',
    fileName: 'vibevoice-voice-de-Spk1_woman.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-de-Spk1_woman.gguf',
    sizeBytes: 4321888,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 4.1 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-emma': ModelDefinition(
    name: 'vibevoice-voice-emma',
    displayName: 'VibeVoice Realtime 0.5B voice — emma',
    fileName: 'vibevoice-voice-emma.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-emma.gguf',
    sizeBytes: 2740832,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 2.6 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-en-Carter_man': ModelDefinition(
    name: 'vibevoice-voice-en-Carter_man',
    displayName: 'VibeVoice Realtime 0.5B voice — en-Carter_man',
    fileName: 'vibevoice-voice-en-Carter_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-en-Carter_man.gguf',
    sizeBytes: 3476064,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 3.3 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-en-Davis_man': ModelDefinition(
    name: 'vibevoice-voice-en-Davis_man',
    displayName: 'VibeVoice Realtime 0.5B voice — en-Davis_man',
    fileName: 'vibevoice-voice-en-Davis_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-en-Davis_man.gguf',
    sizeBytes: 2015840,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 1.9 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-en-Emma_woman': ModelDefinition(
    name: 'vibevoice-voice-en-Emma_woman',
    displayName: 'VibeVoice Realtime 0.5B voice — en-Emma_woman',
    fileName: 'vibevoice-voice-en-Emma_woman.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-en-Emma_woman.gguf',
    sizeBytes: 2740832,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 2.6 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-en-Frank_man': ModelDefinition(
    name: 'vibevoice-voice-en-Frank_man',
    displayName: 'VibeVoice Realtime 0.5B voice — en-Frank_man',
    fileName: 'vibevoice-voice-en-Frank_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-en-Frank_man.gguf',
    sizeBytes: 2757216,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 2.6 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-en-Grace_woman': ModelDefinition(
    name: 'vibevoice-voice-en-Grace_woman',
    displayName: 'VibeVoice Realtime 0.5B voice — en-Grace_woman',
    fileName: 'vibevoice-voice-en-Grace_woman.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-en-Grace_woman.gguf',
    sizeBytes: 2275936,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 2.2 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-en-Mike_man': ModelDefinition(
    name: 'vibevoice-voice-en-Mike_man',
    displayName: 'VibeVoice Realtime 0.5B voice — en-Mike_man',
    fileName: 'vibevoice-voice-en-Mike_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-en-Mike_man.gguf',
    sizeBytes: 1634912,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 1.6 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-fr-Spk0_man': ModelDefinition(
    name: 'vibevoice-voice-fr-Spk0_man',
    displayName: 'VibeVoice Realtime 0.5B voice — fr-Spk0_man',
    fileName: 'vibevoice-voice-fr-Spk0_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-fr-Spk0_man.gguf',
    sizeBytes: 3568224,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 3.4 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-fr-Spk1_woman': ModelDefinition(
    name: 'vibevoice-voice-fr-Spk1_woman',
    displayName: 'VibeVoice Realtime 0.5B voice — fr-Spk1_woman',
    fileName: 'vibevoice-voice-fr-Spk1_woman.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-fr-Spk1_woman.gguf',
    sizeBytes: 3453536,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 3.3 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-in-Samuel_man': ModelDefinition(
    name: 'vibevoice-voice-in-Samuel_man',
    displayName: 'VibeVoice Realtime 0.5B voice — in-Samuel_man',
    fileName: 'vibevoice-voice-in-Samuel_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-in-Samuel_man.gguf',
    sizeBytes: 3101280,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 3.0 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-it-Spk0_woman': ModelDefinition(
    name: 'vibevoice-voice-it-Spk0_woman',
    displayName: 'VibeVoice Realtime 0.5B voice — it-Spk0_woman',
    fileName: 'vibevoice-voice-it-Spk0_woman.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-it-Spk0_woman.gguf',
    sizeBytes: 2081376,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 2.0 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-it-Spk1_man': ModelDefinition(
    name: 'vibevoice-voice-it-Spk1_man',
    displayName: 'VibeVoice Realtime 0.5B voice — it-Spk1_man',
    fileName: 'vibevoice-voice-it-Spk1_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-it-Spk1_man.gguf',
    sizeBytes: 2323040,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 2.2 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-jp-Spk0_man': ModelDefinition(
    name: 'vibevoice-voice-jp-Spk0_man',
    displayName: 'VibeVoice Realtime 0.5B voice — jp-Spk0_man',
    fileName: 'vibevoice-voice-jp-Spk0_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-jp-Spk0_man.gguf',
    sizeBytes: 3787360,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 3.6 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-jp-Spk1_woman': ModelDefinition(
    name: 'vibevoice-voice-jp-Spk1_woman',
    displayName: 'VibeVoice Realtime 0.5B voice — jp-Spk1_woman',
    fileName: 'vibevoice-voice-jp-Spk1_woman.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-jp-Spk1_woman.gguf',
    sizeBytes: 3770976,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 3.6 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-kr-Spk0_woman': ModelDefinition(
    name: 'vibevoice-voice-kr-Spk0_woman',
    displayName: 'VibeVoice Realtime 0.5B voice — kr-Spk0_woman',
    fileName: 'vibevoice-voice-kr-Spk0_woman.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-kr-Spk0_woman.gguf',
    sizeBytes: 3367520,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 3.2 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-kr-Spk1_man': ModelDefinition(
    name: 'vibevoice-voice-kr-Spk1_man',
    displayName: 'VibeVoice Realtime 0.5B voice — kr-Spk1_man',
    fileName: 'vibevoice-voice-kr-Spk1_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-kr-Spk1_man.gguf',
    sizeBytes: 4731488,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 4.5 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-nl-Spk0_man': ModelDefinition(
    name: 'vibevoice-voice-nl-Spk0_man',
    displayName: 'VibeVoice Realtime 0.5B voice — nl-Spk0_man',
    fileName: 'vibevoice-voice-nl-Spk0_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-nl-Spk0_man.gguf',
    sizeBytes: 2986592,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 2.8 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-nl-Spk1_woman': ModelDefinition(
    name: 'vibevoice-voice-nl-Spk1_woman',
    displayName: 'VibeVoice Realtime 0.5B voice — nl-Spk1_woman',
    fileName: 'vibevoice-voice-nl-Spk1_woman.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-nl-Spk1_woman.gguf',
    sizeBytes: 4137568,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 3.9 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-pl-Spk0_man': ModelDefinition(
    name: 'vibevoice-voice-pl-Spk0_man',
    displayName: 'VibeVoice Realtime 0.5B voice — pl-Spk0_man',
    fileName: 'vibevoice-voice-pl-Spk0_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-pl-Spk0_man.gguf',
    sizeBytes: 3041888,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 2.9 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-pl-Spk1_woman': ModelDefinition(
    name: 'vibevoice-voice-pl-Spk1_woman',
    displayName: 'VibeVoice Realtime 0.5B voice — pl-Spk1_woman',
    fileName: 'vibevoice-voice-pl-Spk1_woman.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-pl-Spk1_woman.gguf',
    sizeBytes: 4059744,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 3.9 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-pt-Spk0_woman': ModelDefinition(
    name: 'vibevoice-voice-pt-Spk0_woman',
    displayName: 'VibeVoice Realtime 0.5B voice — pt-Spk0_woman',
    fileName: 'vibevoice-voice-pt-Spk0_woman.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-pt-Spk0_woman.gguf',
    sizeBytes: 1845856,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 1.8 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-pt-Spk1_man': ModelDefinition(
    name: 'vibevoice-voice-pt-Spk1_man',
    displayName: 'VibeVoice Realtime 0.5B voice — pt-Spk1_man',
    fileName: 'vibevoice-voice-pt-Spk1_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-pt-Spk1_man.gguf',
    sizeBytes: 2880096,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 2.7 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-sp-Spk0_woman': ModelDefinition(
    name: 'vibevoice-voice-sp-Spk0_woman',
    displayName: 'VibeVoice Realtime 0.5B voice — sp-Spk0_woman',
    fileName: 'vibevoice-voice-sp-Spk0_woman.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-sp-Spk0_woman.gguf',
    sizeBytes: 3457632,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 3.3 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'vibevoice-voice-sp-Spk1_man': ModelDefinition(
    name: 'vibevoice-voice-sp-Spk1_man',
    displayName: 'VibeVoice Realtime 0.5B voice — sp-Spk1_man',
    fileName: 'vibevoice-voice-sp-Spk1_man.gguf',
    url: 'https://huggingface.co/cstr/vibevoice-realtime-0.5b-GGUF/resolve/main/vibevoice-voice-sp-Spk1_man.gguf',
    sizeBytes: 4186720,
    checksum: '',
    description: 'VibeVoice Realtime 0.5B voicepack — 4.0 MB',
    quantization: 'f16',
    backend: 'vibevoice-tts',
    kind: ModelKind.voice,
  ),
  'mimo-asr-f16': ModelDefinition(
    name: 'mimo-asr-f16',
    displayName: 'MiMo ASR (f16)',
    fileName: 'mimo-asr-f16.gguf',
    url: 'https://huggingface.co/cstr/mimo-asr-GGUF/resolve/main/mimo-asr-f16.gguf',
    sizeBytes: 16043804896,
    checksum: '',
    description: 'XiaomiMiMo MiMo-Audio ASR — 14.94 GB',
    quantization: 'f16',
    backend: 'mimo-asr',
    kind: ModelKind.asr,
  ),
  'mimo-asr-q4_k': ModelDefinition(
    name: 'mimo-asr-q4_k',
    displayName: 'MiMo ASR (q4_k)',
    fileName: 'mimo-asr-q4_k.gguf',
    url: 'https://huggingface.co/cstr/mimo-asr-GGUF/resolve/main/mimo-asr-q4_k.gguf',
    sizeBytes: 4517988832,
    checksum: '',
    description: 'XiaomiMiMo MiMo-Audio ASR — 4.21 GB',
    quantization: 'q4_k',
    backend: 'mimo-asr',
    kind: ModelKind.asr,
  ),
  'kokoro-82m-f16': ModelDefinition(
    name: 'kokoro-82m-f16',
    displayName: 'Kokoro 82M TTS (f16)',
    fileName: 'kokoro-82m-f16.gguf',
    url: 'https://huggingface.co/cstr/kokoro-82m-GGUF/resolve/main/kokoro-82m-f16.gguf',
    sizeBytes: 163728096,
    checksum: '',
    description: 'Kokoro multilingual TTS (~100 MB) — 156.1 MB',
    quantization: 'f16',
    backend: 'kokoro',
    kind: ModelKind.tts,
  ),
  'kokoro-82m-q8_0': ModelDefinition(
    name: 'kokoro-82m-q8_0',
    displayName: 'Kokoro 82M TTS (q8_0)',
    fileName: 'kokoro-82m-q8_0.gguf',
    url: 'https://huggingface.co/cstr/kokoro-82m-GGUF/resolve/main/kokoro-82m-q8_0.gguf',
    sizeBytes: 141322336,
    checksum: '',
    description: 'Kokoro multilingual TTS (~100 MB) — 134.8 MB',
    quantization: 'q8_0',
    backend: 'kokoro',
    kind: ModelKind.tts,
  ),
  'kokoro-voice-af_heart': ModelDefinition(
    name: 'kokoro-voice-af_heart',
    displayName: 'Kokoro 82M TTS voice — af_heart',
    fileName: 'kokoro-voice-af_heart.gguf',
    url: 'https://huggingface.co/cstr/kokoro-voices-GGUF/resolve/main/kokoro-voice-af_heart.gguf',
    sizeBytes: 522560,
    checksum: '',
    description: 'Kokoro 82M TTS voicepack — 510.3 KB',
    quantization: 'f16',
    backend: 'kokoro',
    kind: ModelKind.voice,
  ),
  'kokoro-voice-df_eva': ModelDefinition(
    name: 'kokoro-voice-df_eva',
    displayName: 'Kokoro 82M TTS voice — df_eva',
    fileName: 'kokoro-voice-df_eva.gguf',
    url: 'https://huggingface.co/cstr/kokoro-voices-GGUF/resolve/main/kokoro-voice-df_eva.gguf',
    sizeBytes: 524608,
    checksum: '',
    description: 'Kokoro 82M TTS voicepack — 512.3 KB',
    quantization: 'f16',
    backend: 'kokoro',
    kind: ModelKind.voice,
  ),
  'kokoro-voice-df_victoria': ModelDefinition(
    name: 'kokoro-voice-df_victoria',
    displayName: 'Kokoro 82M TTS voice — df_victoria',
    fileName: 'kokoro-voice-df_victoria.gguf',
    url: 'https://huggingface.co/cstr/kokoro-voices-GGUF/resolve/main/kokoro-voice-df_victoria.gguf',
    sizeBytes: 522560,
    checksum: '',
    description: 'Kokoro 82M TTS voicepack — 510.3 KB',
    quantization: 'f16',
    backend: 'kokoro',
    kind: ModelKind.voice,
  ),
  'kokoro-voice-dm_bernd': ModelDefinition(
    name: 'kokoro-voice-dm_bernd',
    displayName: 'Kokoro 82M TTS voice — dm_bernd',
    fileName: 'kokoro-voice-dm_bernd.gguf',
    url: 'https://huggingface.co/cstr/kokoro-voices-GGUF/resolve/main/kokoro-voice-dm_bernd.gguf',
    sizeBytes: 524608,
    checksum: '',
    description: 'Kokoro 82M TTS voicepack — 512.3 KB',
    quantization: 'f16',
    backend: 'kokoro',
    kind: ModelKind.voice,
  ),
  'kokoro-voice-dm_martin': ModelDefinition(
    name: 'kokoro-voice-dm_martin',
    displayName: 'Kokoro 82M TTS voice — dm_martin',
    fileName: 'kokoro-voice-dm_martin.gguf',
    url: 'https://huggingface.co/cstr/kokoro-voices-GGUF/resolve/main/kokoro-voice-dm_martin.gguf',
    sizeBytes: 522560,
    checksum: '',
    description: 'Kokoro 82M TTS voicepack — 510.3 KB',
    quantization: 'f16',
    backend: 'kokoro',
    kind: ModelKind.voice,
  ),
  'kokoro-voice-ef_dora': ModelDefinition(
    name: 'kokoro-voice-ef_dora',
    displayName: 'Kokoro 82M TTS voice — ef_dora',
    fileName: 'kokoro-voice-ef_dora.gguf',
    url: 'https://huggingface.co/cstr/kokoro-voices-GGUF/resolve/main/kokoro-voice-ef_dora.gguf',
    sizeBytes: 522560,
    checksum: '',
    description: 'Kokoro 82M TTS voicepack — 510.3 KB',
    quantization: 'f16',
    backend: 'kokoro',
    kind: ModelKind.voice,
  ),
  'kokoro-voice-ff_siwis': ModelDefinition(
    name: 'kokoro-voice-ff_siwis',
    displayName: 'Kokoro 82M TTS voice — ff_siwis',
    fileName: 'kokoro-voice-ff_siwis.gguf',
    url: 'https://huggingface.co/cstr/kokoro-voices-GGUF/resolve/main/kokoro-voice-ff_siwis.gguf',
    sizeBytes: 522560,
    checksum: '',
    description: 'Kokoro 82M TTS voicepack — 510.3 KB',
    quantization: 'f16',
    backend: 'kokoro',
    kind: ModelKind.voice,
  ),
  'orpheus-3b-base-f16': ModelDefinition(
    name: 'orpheus-3b-base-f16',
    displayName: 'Orpheus 3B TTS (f16)',
    fileName: 'orpheus-3b-base-f16.gguf',
    url: 'https://huggingface.co/cstr/orpheus-3b-base-GGUF/resolve/main/orpheus-3b-base-f16.gguf',
    sizeBytes: 6610198752,
    checksum: '',
    description: 'Orpheus Llama-3.2-3B TTS (~3.5 GB) — 6.16 GB',
    quantization: 'f16',
    backend: 'orpheus',
    kind: ModelKind.tts,
  ),
  'orpheus-3b-base-q8_0': ModelDefinition(
    name: 'orpheus-3b-base-q8_0',
    displayName: 'Orpheus 3B TTS (q8_0)',
    fileName: 'orpheus-3b-base-q8_0.gguf',
    url: 'https://huggingface.co/cstr/orpheus-3b-base-GGUF/resolve/main/orpheus-3b-base-q8_0.gguf',
    sizeBytes: 3515800128,
    checksum: '',
    description: 'Orpheus Llama-3.2-3B TTS (~3.5 GB) — 3.27 GB',
    quantization: 'q8_0',
    backend: 'orpheus',
    kind: ModelKind.tts,
  ),
  'fireredpunc-q4_k': ModelDefinition(
    name: 'fireredpunc-q4_k',
    displayName: 'FireRedPunc (post-processor) (q4_k)',
    fileName: 'fireredpunc-q4_k.gguf',
    url: 'https://huggingface.co/cstr/fireredpunc-GGUF/resolve/main/fireredpunc-q4_k.gguf',
    sizeBytes: 57886944,
    checksum: '',
    description: 'Punctuation restoration for CTC ASR output — 55.2 MB',
    quantization: 'q4_k',
    backend: 'firered-punc',
    kind: ModelKind.punc,
  ),
  'fireredpunc-q8_0': ModelDefinition(
    name: 'fireredpunc-q8_0',
    displayName: 'FireRedPunc (post-processor) (q8_0)',
    fileName: 'fireredpunc-q8_0.gguf',
    url: 'https://huggingface.co/cstr/fireredpunc-GGUF/resolve/main/fireredpunc-q8_0.gguf',
    sizeBytes: 108664800,
    checksum: '',
    description: 'Punctuation restoration for CTC ASR output — 103.6 MB',
    quantization: 'q8_0',
    backend: 'firered-punc',
    kind: ModelKind.punc,
  ),
  'fireredpunc-f16': ModelDefinition(
    name: 'fireredpunc-f16',
    displayName: 'FireRedPunc (post-processor) (f16)',
    fileName: 'fireredpunc.gguf',
    url: 'https://huggingface.co/cstr/fireredpunc-GGUF/resolve/main/fireredpunc.gguf',
    sizeBytes: 203873216,
    checksum: '',
    description: 'Punctuation restoration for CTC ASR output — 194.4 MB',
    quantization: 'f16',
    backend: 'firered-punc',
    kind: ModelKind.punc,
  ),
  'granite-speech-4.1-2b-f16': ModelDefinition(
    name: 'granite-speech-4.1-2b-f16',
    displayName: 'Granite Speech 4.1 2B (f16)',
    fileName: 'granite-speech-4.1-2b-f16.gguf',
    url: 'https://huggingface.co/cstr/granite-speech-4.1-2b-GGUF/resolve/main/granite-speech-4.1-2b-f16.gguf',
    sizeBytes: 5581887616,
    checksum: '',
    description: 'IBM Granite Speech 4.1 (2B) — 5.20 GB',
    quantization: 'f16',
    backend: 'granite-4.1',
    kind: ModelKind.asr,
  ),
  'granite-speech-4.1-2b-q4_k-f16enc': ModelDefinition(
    name: 'granite-speech-4.1-2b-q4_k-f16enc',
    displayName: 'Granite Speech 4.1 2B (q4_k-f16enc)',
    fileName: 'granite-speech-4.1-2b-q4_k-f16enc.gguf',
    url: 'https://huggingface.co/cstr/granite-speech-4.1-2b-GGUF/resolve/main/granite-speech-4.1-2b-q4_k-f16enc.gguf',
    sizeBytes: 2268201440,
    checksum: '',
    description: 'IBM Granite Speech 4.1 (2B) — 2.11 GB',
    quantization: 'q4_k-f16enc',
    backend: 'granite-4.1',
    kind: ModelKind.asr,
  ),
  'granite-speech-4.1-2b-q4_k-mini': ModelDefinition(
    name: 'granite-speech-4.1-2b-q4_k-mini',
    displayName: 'Granite Speech 4.1 2B (q4_k-mini)',
    fileName: 'granite-speech-4.1-2b-q4_k-mini.gguf',
    url: 'https://huggingface.co/cstr/granite-speech-4.1-2b-GGUF/resolve/main/granite-speech-4.1-2b-q4_k-mini.gguf',
    sizeBytes: 1778605792,
    checksum: '',
    description: 'IBM Granite Speech 4.1 (2B) — 1.66 GB',
    quantization: 'q4_k-mini',
    backend: 'granite-4.1',
    kind: ModelKind.asr,
  ),
  'granite-speech-4.1-2b-q4_k': ModelDefinition(
    name: 'granite-speech-4.1-2b-q4_k',
    displayName: 'Granite Speech 4.1 2B (q4_k)',
    fileName: 'granite-speech-4.1-2b-q4_k.gguf',
    url: 'https://huggingface.co/cstr/granite-speech-4.1-2b-GGUF/resolve/main/granite-speech-4.1-2b-q4_k.gguf',
    sizeBytes: 2941043168,
    checksum: '',
    description: 'IBM Granite Speech 4.1 (2B) — 2.74 GB',
    quantization: 'q4_k',
    backend: 'granite-4.1',
    kind: ModelKind.asr,
  ),
  'm2m100-418m-f16': ModelDefinition(
    name: 'm2m100-418m-f16',
    displayName: 'M2M-100 418M (f16)',
    fileName: 'm2m100-418m-f16.gguf',
    url: 'https://huggingface.co/cstr/m2m100-418m-GGUF/resolve/main/m2m100-418m-f16.gguf',
    sizeBytes: 979611456,
    checksum: '',
    description: 'Text-to-text translation (100 languages, any-to-any) — 934.2 MB',
    quantization: 'f16',
    backend: 'm2m100',
    kind: ModelKind.translate,
  ),
  'm2m100-418m-q4_k': ModelDefinition(
    name: 'm2m100-418m-q4_k',
    displayName: 'M2M-100 418M (q4_k)',
    fileName: 'm2m100-418m-q4_k.gguf',
    url: 'https://huggingface.co/cstr/m2m100-418m-GGUF/resolve/main/m2m100-418m-q4_k.gguf',
    sizeBytes: 284568416,
    checksum: '',
    description: 'Text-to-text translation (100 languages, any-to-any) — 271.4 MB',
    quantization: 'q4_k',
    backend: 'm2m100',
    kind: ModelKind.translate,
  ),
  'm2m100-418m-q8_0': ModelDefinition(
    name: 'm2m100-418m-q8_0',
    displayName: 'M2M-100 418M (q8_0)',
    fileName: 'm2m100-418m-q8_0.gguf',
    url: 'https://huggingface.co/cstr/m2m100-418m-GGUF/resolve/main/m2m100-418m-q8_0.gguf',
    sizeBytes: 526322528,
    checksum: '',
    description: 'Text-to-text translation (100 languages, any-to-any) — 501.9 MB',
    quantization: 'q8_0',
    backend: 'm2m100',
    kind: ModelKind.translate,
  ),
  'wmt21-dense-24-wide-en-x-f16': ModelDefinition(
    name: 'wmt21-dense-24-wide-en-x-f16',
    displayName: 'WMT21 Dense 24-wide en→X (f16)',
    fileName: 'wmt21-dense-24-wide-en-x-f16.gguf',
    url: 'https://huggingface.co/cstr/wmt21-dense-24-wide-en-x-GGUF/resolve/main/wmt21-dense-24-wide-en-x-f16.gguf',
    sizeBytes: 9410193472,
    checksum: '',
    description: 'WMT21 News winner — English to 7 target languages — 8.76 GB',
    quantization: 'f16',
    backend: 'm2m100-wmt21',
    kind: ModelKind.translate,
  ),
  'wmt21-dense-24-wide-en-x-q4_k': ModelDefinition(
    name: 'wmt21-dense-24-wide-en-x-q4_k',
    displayName: 'WMT21 Dense 24-wide en→X (q4_k)',
    fileName: 'wmt21-dense-24-wide-en-x-q4_k.gguf',
    url: 'https://huggingface.co/cstr/wmt21-dense-24-wide-en-x-GGUF/resolve/main/wmt21-dense-24-wide-en-x-q4_k.gguf',
    sizeBytes: 2666381568,
    checksum: '',
    description: 'WMT21 News winner — English to 7 target languages — 2.48 GB',
    quantization: 'q4_k',
    backend: 'm2m100-wmt21',
    kind: ModelKind.translate,
  ),
  'wmt21-dense-24-wide-en-x-q8_0': ModelDefinition(
    name: 'wmt21-dense-24-wide-en-x-q8_0',
    displayName: 'WMT21 Dense 24-wide en→X (q8_0)',
    fileName: 'wmt21-dense-24-wide-en-x-q8_0.gguf',
    url: 'https://huggingface.co/cstr/wmt21-dense-24-wide-en-x-GGUF/resolve/main/wmt21-dense-24-wide-en-x-q8_0.gguf',
    sizeBytes: 5012055296,
    checksum: '',
    description: 'WMT21 News winner — English to 7 target languages — 4.67 GB',
    quantization: 'q8_0',
    backend: 'm2m100-wmt21',
    kind: ModelKind.translate,
  ),
  'wmt21-dense-24-wide-x-en-f16': ModelDefinition(
    name: 'wmt21-dense-24-wide-x-en-f16',
    displayName: 'WMT21 Dense 24-wide X→en (f16)',
    fileName: 'wmt21-dense-24-wide-x-en-f16.gguf',
    url: 'https://huggingface.co/cstr/wmt21-dense-24-wide-x-en-GGUF/resolve/main/wmt21-dense-24-wide-x-en-f16.gguf',
    sizeBytes: 9410194592,
    checksum: '',
    description: 'WMT21 News winner — 7 source languages to English — 8.76 GB',
    quantization: 'f16',
    backend: 'm2m100-wmt21',
    kind: ModelKind.translate,
  ),
  'wmt21-dense-24-wide-x-en-q4_k': ModelDefinition(
    name: 'wmt21-dense-24-wide-x-en-q4_k',
    displayName: 'WMT21 Dense 24-wide X→en (q4_k)',
    fileName: 'wmt21-dense-24-wide-x-en-q4_k.gguf',
    url: 'https://huggingface.co/cstr/wmt21-dense-24-wide-x-en-GGUF/resolve/main/wmt21-dense-24-wide-x-en-q4_k.gguf',
    sizeBytes: 2666382688,
    checksum: '',
    description: 'WMT21 News winner — 7 source languages to English — 2.48 GB',
    quantization: 'q4_k',
    backend: 'm2m100-wmt21',
    kind: ModelKind.translate,
  ),
  'wmt21-dense-24-wide-x-en-q8_0': ModelDefinition(
    name: 'wmt21-dense-24-wide-x-en-q8_0',
    displayName: 'WMT21 Dense 24-wide X→en (q8_0)',
    fileName: 'wmt21-dense-24-wide-x-en-q8_0.gguf',
    url: 'https://huggingface.co/cstr/wmt21-dense-24-wide-x-en-GGUF/resolve/main/wmt21-dense-24-wide-x-en-q8_0.gguf',
    sizeBytes: 5012056416,
    checksum: '',
    description: 'WMT21 News winner — 7 source languages to English — 4.67 GB',
    quantization: 'q8_0',
    backend: 'm2m100-wmt21',
    kind: ModelKind.translate,
  ),
  'madlad400-3b-mt-q4_k': ModelDefinition(
    name: 'madlad400-3b-mt-q4_k',
    displayName: 'MADLAD-400 3B-MT (q4_k)',
    fileName: 'madlad400-3b-mt-q4_k.gguf',
    url: 'https://huggingface.co/cstr/madlad400-3b-mt-GGUF/resolve/main/madlad400-3b-mt-q4_k.gguf',
    sizeBytes: 2036588352,
    checksum: '',
    description: 'T5 translator, 419 languages — 1.90 GB',
    quantization: 'q4_k',
    backend: 'madlad',
    kind: ModelKind.translate,
  ),
};
